spring.application.name=demosupermercado

# =====================
# DATASOURCE (H2) Demo
# =====================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# ========================
# JPA / HIBERNATE / MySQL
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.propierties.hibernate.dialect=${DB_PLATFORM}
server.port=8080
